"""initial_schema_voxshield

Revision ID: b7ff62f7830b
Revises: 
Create Date: 2026-09-08 23:17:53.254850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ff62f7830b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.add_column('trusted_devices', sa.Column('device_token_hash', sa.String(length=128), nullable=True))
    op.add_column('trusted_devices', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    op.create_index(op.f('ix_trusted_devices_device_token_hash'), 'trusted_devices', ['device_token_hash'], unique=False)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('voice_commands', sa.Column('device_id', sa.String(length=36), nullable=True))
    op.add_column('voice_commands', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('voice_commands', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('voice_commands', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'APPROVAL_REQUIRED', 'APPROVED', 'CLAIMED', 'EXECUTING', 'EXECUTED', 'BLOCKED', 'REJECTED', 'EXPIRED', 'FAILED', name='commandstatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_voice_commands_device_id'), 'voice_commands', ['device_id'], unique=False)
    op.create_foreign_key(None, 'voice_commands', 'trusted_devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_commands', type_='foreignkey')
    op.drop_index(op.f('ix_voice_commands_device_id'), table_name='voice_commands')
    op.alter_column('voice_commands', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVAL_REQUIRED', 'APPROVED', 'CLAIMED', 'EXECUTING', 'EXECUTED', 'BLOCKED', 'REJECTED', 'EXPIRED', 'FAILED', name='commandstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('voice_commands', 'expires_at')
    op.drop_column('voice_commands', 'claimed_at')
    op.drop_column('voice_commands', 'device_id')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_trusted_devices_device_token_hash'), table_name='trusted_devices')
    op.drop_column('trusted_devices', 'status')
    op.drop_column('trusted_devices', 'device_token_hash')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
